### ISSUE TITLE
Vise bedrift hvis flere forfattere kommer fra ulike bedrifter

### ISSUE THREAD

**Issue by tonenordbo** [UX-Norge/ux-norge#18]

**Comment by simjes** [comment]
Er det her dette ønskes?

![Image](https://user-images.githubusercontent.com/6494049/225077835-65004b04-95c3-45d5-ba8e-06b9f36cf7bf.png)

**Comment by tonenordbo** [comment]
Ja, her er et eksempel med bedrift. Noen ganger er det to forfattere som er fra forskjellige bedrifter.
https://uxnorge.no/kjaere-alle-ux-ere/

**Comment by simjes** [comment]
Hvis artikkelen har flere forfattere og alle er fra samme firma (og ikke fra UX Norge), skal det da ikke vises firma her? Eller ville det blitt som på bildet?

![Image](https://user-images.githubusercontent.com/6494049/225092231-747e5488-1a82-4fc8-b438-fc411aaa6e59.png)

 
Jeg har en pull request, men lar den ligge i draft til spørsmålet er avklart. #47

**Comment by tonenordbo** [comment]
Jo, hvis alle er fra samme firma skal det vises slik som her: https://uxnorge.no/hoydepunkter-fra-south-by-southwest-sxsw/

**Comment by tonenordbo** [comment]
Løsningen du viser over her er veldig fin hvis det er to personer fra forskjellige firmaer!

**Comment by simjes** [comment]
Ser disse greie ut 😄 ?

![Image](https://user-images.githubusercontent.com/6494049/225100734-d5ee669b-7466-4305-9912-07c887394b12.png)
