### ISSUE TITLE
Tweak av visning av forsiden på mobil

### ISSUE THREAD

**Issue by tonenordbo** [UX-Norge/ux-norge#22]
Ser sånn ut på Safari, iphone 11:

![Image](https://user-images.githubusercontent.com/21240822/187192758-e25e0b8f-8e6f-4a72-b157-1e7a6546dfe0.png)

**Comment by TobWul** [comment]
Huskelapp: En text-break eller justere font-størrelsen burde løse dette

**Comment by TobWul** [comment]
Duplikat av #33
