### ISSUE TITLE
Fikse relatert artikkel i teksten

### ISSUE THREAD

**Issue by tonenordbo** [UX-Norge/ux-norge#30]

**Comment by tonenordbo** [comment]
Er noe rart med visning av relaterte artikler i Safari på desktop, bildene blir kuttet og veldig lange. Ser bra ut i Chrome, Firefox og på mobil.

**Comment by simjes** [comment]
Ser ut som denne er grei, og ligger i done. Lukker, gjenåpne hvis den ikke er ok.
