### ISSUE TITLE
Kurs: mulighet for flere kursholdere på et kurs

### ISSUE THREAD

**Issue by tonenordbo** [UX-Norge/ux-norge#44]

**Comment by ksannaes** [comment]
Det finnes en pull request, den må testes først. Eksisterende kurs må migreres til ny datamodell.

**Comment by einarstubhaug** [comment]
Har laget migreringsscript og lagt til mulighet for flere kursholdere i schemaet. Kursholderne blir foreløpig vist for publikum med komma i mellom dem.
