### ISSUE TITLE
Det legger seg gamle stillingsannonser i sakene:

### ISSUE THREAD

**Issue by tonenordbo** [UX-Norge/ux-norge#69]
Det legger seg gamle stillingsannonser i sakene: 

![Image](https://user-images.githubusercontent.com/140154891/257163080-fd0cdd41-225f-40e7-acec-b893fe2bb3bc.png)
![Image](https://user-images.githubusercontent.com/140154891/257163081-35850a95-ac28-4f9d-8ee4-e7afaf6c8125.png)

**Comment by einarstubhaug** [comment]
Det manglet deadline-info.
