### ISSUE TITLE
Oppdatere bokmerkeikon

### ISSUE THREAD

**Issue by tonenordbo** [UX-Norge/ux-norge#78]
Bokmerkeikonet som legger seg på bokmerkelinjen er av en eller annen grunn den gamle logoen, og ikke favikonet med den nye logoen, er det mulig å fikse det?

**Comment by simjes** [comment]
Ser ut som denne ikke lenger er relevant siden den ikke ligger i project boardet. Lukker den.

I tilfelle den gjenåpnes:
Ser ut som dette håndteres av [gatsby-plugin-manifest](https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/) i `gatsby-config.js`.
